name: black
on:
  push:
    branches: main
    paths:
      - '**.py'
      - .github/workflows/black.yml
      - 'pyproject.toml'
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/black.yml
      - 'pyproject.toml'
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      # Installation instructions are from: https://python-poetry.org/docs/
      - name: Install dependencies
        shell: bash
        run: |
          pip install \
          poetry

      - name: Build
        shell: bash
        run: |
          poetry install
          poetry build

      - name: Run black
        shell: bash
        run: |
          poetry run black --check --diff . generate/generate.py docs/conf.py kittycad/client_test.py kittycad/examples_test.py
