name: generate docs
permissions:
  contents: write
on:
  push:
    branches: main
    paths:
      - '**.py'
      - .github/workflows/generate-docs.yml
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/generate-docs.yml
jobs:
  generate-docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Installation instructions are from: https://python-poetry.org/docs/
      - name: Install dependencies
        shell: bash
        run: |
          pip install \
          poetry

      - name: Build
        shell: bash
        run: |
          poetry build

      - name: Generate the docs
        shell: bash
        run: |
          pydoc3 -w kittycad

